theme: jekyll-theme-cayman
timezone: TIMEZONE
future: true

title: [IFB / Elixir-FR interoperability working group]
description: [Interoperability resources and guidelines for bioinformatics]

author: 
 - Thomas Rosnet
 - Alban Gaignard
 - Marie-Dominique Devignes
 
isPartOf: https://www.france-bioinformatique.fr
